// Code generated by mockery v2.30.1. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// URLShortner is an autogenerated mock type for the URLShortner type
type URLShortner struct {
	mock.Mock
}

// CreateShortPath provides a mock function with given fields: ctx, shortPath, targetURL
func (_m *URLShortner) CreateShortPath(ctx context.Context, shortPath string, targetURL string) (string, error) {
	ret := _m.Called(ctx, shortPath, targetURL)

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) (string, error)); ok {
		return rf(ctx, shortPath, targetURL)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string) string); ok {
		r0 = rf(ctx, shortPath, targetURL)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = rf(ctx, shortPath, targetURL)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetTargetURL provides a mock function with given fields: ctx, shortPath
func (_m *URLShortner) GetTargetURL(ctx context.Context, shortPath string) (string, error) {
	ret := _m.Called(ctx, shortPath)

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (string, error)); ok {
		return rf(ctx, shortPath)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) string); ok {
		r0 = rf(ctx, shortPath)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, shortPath)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewURLShortner creates a new instance of URLShortner. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewURLShortner(t interface {
	mock.TestingT
	Cleanup(func())
}) *URLShortner {
	mock := &URLShortner{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
