// Code generated by mockery v2.30.1. DO NOT EDIT.

package mocks

import (
	mock "github.com/stretchr/testify/mock"
	metrics "github.com/thenilesh/url-shortner/metrics"
)

// Metrics is an autogenerated mock type for the Metrics type
type Metrics struct {
	mock.Mock
}

// GetCollector provides a mock function with given fields: name
func (_m *Metrics) GetCollector(name string) metrics.Collector {
	ret := _m.Called(name)

	var r0 metrics.Collector
	if rf, ok := ret.Get(0).(func(string) metrics.Collector); ok {
		r0 = rf(name)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(metrics.Collector)
		}
	}

	return r0
}

// Start provides a mock function with given fields:
func (_m *Metrics) Start() {
	_m.Called()
}

// NewMetrics creates a new instance of Metrics. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMetrics(t interface {
	mock.TestingT
	Cleanup(func())
}) *Metrics {
	mock := &Metrics{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
